default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: rails-env_development

production:
  <<: *default
  database: rails-env_production
  username: rails-env
  password: <%= ENV['RAILS-ENV_DATABASE_PASSWORD'] %>
